### ISSUE TITLE
Alexa recognizes my command but the garage door doesn't open or close

### ISSUE THREAD

**Issue by maximuslee1226** [jbnunn/Alexa-MyQGarage#34] opened 2017-03-31 13:28 UTC
Has anyone had this problem where Alexa recognizes my command but the garage door doesn't open or close? Some help here please?

**Comment by SConaway** [comment] 2017-04-01 01:58
Please post the logs from AWS Lambda. Also, can you check the door state. Thanks

**Comment by steve772** [comment] 2017-04-19 08:59
I am having the same issue...Alexa recognizes commands but doors do not respond. Worked fine for many months.   Log:

START RequestId: c6fd0c97-249c-11e7-aa77-df6677471889 Version: $LATEST
MyQDeviceTypeName:VGDO
MyQDeviceId:807478
Number of Devices:1
MyQDeviceTypeName:VGDO
MyQDeviceId:807481
Number of Devices:2
onSessionStarted requestId=amzn1.echo-api.request.6afa75a7-d035-4a3c-92ef-689a72f352e4, sessionId=amzn1.echo-api.session.5e682717-196f-4408-bda4-c62a4123e58f
Change Door State: 807478 to close
Closing...
END RequestId: c6fd0c97-249c-11e7-aa77-df6677471889
REPORT RequestId: c6fd0c97-249c-11e7-aa77-df6677471889	Duration: 2342.96 ms	Billed Duration: 2400 ms Memory Size: 128 MB	Max Memory Used: 24 MB

**Comment by astromgren** [comment] 2017-04-23 20:57
I'm having the same issue after installing for the first time.
-Door state works as intended
-Test Open/Close using Service Simulator works as intended
-Open/Close using Echo does not work

Edit: Maybe it was operator error.  What I meant to say above was I could not say "Ask Garage to open" while that exact syntax seemed to work in the simulator.  After some playing around, I am able to use the  verbal command "Alexa, Ask the garage door to open/close" and it worked great.

**Closed as completed** 2017-05-05 15:13 UTC
